name: SolarWinds Innovate Summit 2017
description: A conference for tech professionals
baseurl: '.'
#baseurl: 'http://innovate.solarwinds.io'
iourl: 'http://solarwinds.io'
# sass:
#     style: compressed