# Basics
name: SolarWinds Innovate Summit 2017
description: A conference for tech professionals
iourl: 'https://solarwinds.io'
repository: solarwinds/innovate.solarwinds.io

# Setup
sass:
  sass_dir: ./_sass
  style: compressed
exclude:
  - _config.yml
  - _deployments/
  - .circleci/
  - .gitignore
  - build.sh
  - CNAME
  - deployment_configs/
  - Dockerfile
  - Dockerfile_ci
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Makefile
  - nginx.conf
  - README.md

# Testing
# baseurl: ''