# Basics
name: SolarWinds Innovate Summit 2017
description: A conference for tech professionals
iourl: 'https://solarwinds.io'
repository: solarwinds/innovate.solarwinds.io

# Setup
sass:
    sass_dir: ./_sass
    style: compressed
exclude: [node_modules, _config.yml, .gitignore, CNAME, Dockerfile, Gemfile, LICENSE, Makefile, package-lock.json, package.json, README.md]

# Testing
# baseurl: ''