# Basics
name: SolarWinds Innovate Summit 2017
description: A conference for tech professionals
# baseurl: 'http://innovate.solarwinds.io'
iourl: 'http://solarwinds.io'

# Setup
sass:
    sass_dir: ./_sass
    style: compressed

# Testing
baseurl: ''
port: 8082
host: 10.110.46.130