version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec jekyll build
      - run: aws s3 sync _site/ s3://innovate.solarwinds.io/ --delete







