version: 2
jobs:
  build:
    working_directory: /app/
    machine: true
    steps:
      - checkout
      - run: jekyll build
      - run: aws s3 sync _site/ s3://innovate.solarwinds.io/ --delete







