version: 2
jobs:
  build:
    working_directory: /app/
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: jekyll/jekyll:3.5.0
    steps:
      - checkout
      - run: jekyll build
      # - run: htmlproofer ./_site --allow-hash-href --check-html --disable-external
      - run: aws s3 sync _site/ s3://innovate.solarwinds.io/ --delete







