#https://gfiboulder.atlassian.net/wiki/spaces/ZEUS/pages/271876388/Hermes+-+Expose+to+the+outside+world+Pods+running+on+Hera
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: innovatesolarwindsio-prod-zeus-systemmonitor-tls-cert
spec:
  acme:
    config:
      - domains:
          - innovate.solarwinds.io
        http01:
          ingressClass: nginx
  dnsNames:
    - innovate.solarwinds.io
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: innovateio-prod-tls-cert
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: innovatesolarwindsio-gateway
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
    - hosts:
        - innovate.solarwinds.io
      secretName: innovateio-prod-tls-cert
  rules:
  - host: innovate.solarwinds.io
    http:
      paths:
      - path: /
        backend:
          serviceName: innovate-service
          servicePort: 80